import codecs

def append_section(title, papers):
    with codecs.open('c:/Users/yatin/Downloads/CAP/Documentation/LocalDemand_Final_Literature_Review.md', 'a', 'utf-8') as out:
        out.write(f"\n## {title}\n\n")
        for paper in papers:
            out.write(f"### {paper['title']}\n")
            if 'details' in paper:
                out.write(paper['details'] + "\n")
            out.write(f"**Literature Review Paragraph:**\n{paper['paragraph']}\n\n---\n\n")

sections = []

# SECTION 1
sec1 = {
    'title': 'Section 1 — Forecasting Methods',
    'papers': [
        {
            'title': 'Comparative Evaluation of SARIMA, FB Prophet, and LSTM for Hourly Demand Forecasting in Saudagar Kopi',
            'details': '**Author(s) & Year:** Kevina Syahla Aqila et al. (2026)\n**Model/Method used:** SARIMA, FB Prophet, Stacked LSTM.\n**Dataset used:** Hourly POS sales data from Saudagar Kopi in Jakarta.\n**Results:** LSTM RMSE = 0.1535, FB Prophet RMSE = 0.46, SARIMA RMSE = 0.5265.\n**Connection to our PS / gap:** Strongly relates to the forecast-to-action gap (3). It successfully predicts volume but does not convert insights into automated inventory decisions, which LocalDemand addresses.',
            'paragraph': 'Recent advancements in demand forecasting have increasingly targeted the operational inefficiencies of small food and beverage businesses. Aqila et al. (2026) conducted a comparative empirical evaluation of SARIMA, FB Prophet, and LSTM models to predict high-frequency, hourly demand at a Jakarta coffee shop. The authors incorporated exogenous variables, such as rush-hour and holiday indicators, to handle significant demand volatility. Their results revealed that while LSTM provided the highest accuracy (RMSE = 0.1535), FB Prophet also produced highly stable and interpretable forecasts (RMSE = 0.46) by effectively managing weekly and daily seasonality. Despite demonstrating that complex time-series models can successfully anticipate peak congestion in SME environments, the study remains purely analytical. It successfully predicts customer volume but fails to translate these insights into automated inventory decisions. LocalDemand addresses this exact limitation by utilizing a Prophet-based architecture not just to forecast sales, but to explicitly generate actionable daily restock recommendations.'
        },
        {
            'title': 'Smart Sales Forecasting Machine Learning Models for Demand Prediction in Retail',
            'details': '**Author(s) & Year:** Sandeep V et al. (2025)\n**Model/Method used:** Hierarchical Agglomerative Clustering (HAC), K-Means, Decision Trees, Linear Regression.\n**Connection to our PS / gap:** Validates the integration of external regressors (weather) to improve accuracy.',
            'paragraph': 'Traditional forecasting methods that rely solely on historical sales data frequently fail to capture the nuances of consumer purchasing behavior, which is heavily influenced by the external environment. Sandeep et al. (2025) addressed this by developing a machine learning framework that incorporates external variables—such as weather conditions and economic indicators—into retail demand prediction. Utilizing K-Means and Hierarchical Agglomerative Clustering, the authors grouped products with similar demand profiles before applying decision trees and linear regression. Their findings indicate that augmenting historical data with environmental regressors significantly enhances forecasting adaptability and accuracy. While the study provides a strong methodological justification for using external data, its reliance on established, static datasets (e.g., Big Mart Sales) limits its applicability to the highly volatile, data-scarce reality of micro-SMEs. LocalDemand adopts the core philosophy of this research—specifically the integration of weather and holiday variables—but executes it using Facebook Prophet to explicitly handle the data scarcity and cold-start problems that standard regression and clustering algorithms struggle to manage.'
        },
        {
            'title': 'State-Level Drug Retail Sales Forecasting Using XGBoost and Facebook Prophet',
            'details': '**Author(s) & Year:** Mohit Kamboj et al. (2025)\n**Model/Method used:** Hybrid Facebook Prophet + XGBoost.\n**Results:** Reduced median state-wise MAPE by 12% to 18%.\n**Connection to our PS / gap:** Empirically validates Prophet’s superiority in retail context handling seasonality and holidays.',
            'paragraph': 'The increasing complexity of modern retail environments has led to the adoption of hybrid machine learning architectures that combine statistical interpretability with nonlinear pattern recognition. Kamboj et al. (2025) demonstrated this by developing a hybrid forecasting framework using Facebook Prophet and XGBoost to predict state-level sales for the Rossmann drugstore chain in Germany. Prophet was utilized to achieve robust time-series decomposition (handling holidays and seasonality), while XGBoost was applied to the residuals to capture the nonlinear effects of internal promotions and competitor proximity. The hybrid model outperformed classical baselines like SARIMA and Holt-Winters, reducing the median state-wise MAPE by 12% to 18%. This study provides powerful empirical validation for Facebook Prophet’s efficacy in retail demand forecasting, particularly regarding its handling of exogenous events like holidays. However, the study’s focus on macro-level (state-wide) forecasting for a massive corporate enterprise means its findings are not directly actionable for single-location SMEs. LocalDemand scales this advanced Prophet-based methodology down to the micro-level, applying it directly to individual menu items to generate accessible, localized restock recommendations for small food businesses.'
        },
        {
            'title': 'Automated Demand Forecasting in Small to Medium-Sized Enterprises',
            'details': '**Author(s) & Year:** Thomas Gärtner et al. (2024)\n**Model/Method used:** ARIMA, SARIMAX, Holt-Winters, XGBoost, Dilated CNN, GAM.\n**Results:** Dilated CNN achieved nRMSE = 0.3119, MAPE = 33.19%.',
            'paragraph': 'Gärtner et al. (2024) presented an automated demand forecasting system to help small and medium-sized enterprises (SMEs) improve their inventory planning and reduce manual forecasting efforts. The study used several forecasting models, including ARIMA, SARIMAX, Holt-Winters, XGBoost, Dilated CNN, and Ensemble models, to identify the most suitable forecasting approach. The results showed that the Dilated CNN model produced the most accurate forecasts and performed better than traditional forecasting methods in most of the SMEs included in the study. The proposed system helps businesses make better inventory decisions without requiring advanced technical knowledge. However, the model mainly depends on historical sales data and does not consider external factors such as weather or holidays. It also requires sufficient historical data, making it less suitable for newly established businesses.'
        },
        {
            'title': 'Enhancing Retail Sales Forecasting with Optimized Machine Learning Models',
            'details': '**Author(s) & Year:** Priyam Ganguly, Isha Mukherjee (2024)\n**Model/Method used:** Random Forest, Linear Regression, Gradient Boosting, SVR, XGBoost.\n**Results:** Optimized Random Forest achieved R² score of 0.945.',
            'paragraph': 'Ganguly and Mukherjee (2024) proposed a machine learning-based approach to improve retail sales forecasting and inventory planning. The study compared different machine learning models such as Linear Regression, Random Forest, Gradient Boosting, Support Vector Regression, and XGBoost using a retail sales dataset. Hyperparameter tuning was applied to improve the performance of the models. The experimental results showed that the optimized Random Forest model achieved the highest forecasting accuracy compared to the other models. The study concluded that machine learning techniques can effectively predict future sales and support better inventory management. However, the research mainly focused on retail stores and did not provide inventory recommendations or consider external factors like weather and holidays. It also did not develop a mobile application for small food businesses.'
        },
        {
            'title': 'Optimization of Forecasting Performance in the Retail Sector Using Artificial Intelligence',
            'details': '**Author(s) & Year:** Hoda Jatte et al. (2025)\n**Model/Method used:** Linear Regression, Decision Tree, Random Forest, XGBoost, Prophet, LSTM.\n**Results:** LSTM achieved 92.31% accuracy, Prophet achieved 85.71% accuracy.',
            'paragraph': 'Jatte et al. (2025) presented a comparative study on optimizing retail demand forecasting using Artificial Intelligence techniques to improve inventory management and supply chain operations. The authors employed six forecasting models, namely Linear Regression, Decision Tree, Random Forest, XGBoost, Prophet, and Long Short-Term Memory (LSTM), using a Kaggle retail demand forecasting dataset containing over 100,000 historical sales records. The methodology included data preprocessing, feature engineering, model training, and performance evaluation using Accuracy, Precision, Recall, F1-score, RMSE, and R² metrics. The experimental results demonstrated that the LSTM model achieved the highest forecasting performance with 92.31% accuracy and 96% F1-score, while the Prophet model also produced reliable forecasting results with 85.71% accuracy. The study concluded that AI-based forecasting models significantly improve demand prediction and inventory planning in the retail sector. However, the research was limited to a public retail dataset and did not validate the proposed models on small food businesses such as bakeries, cafés, and restaurants. Furthermore, the study did not incorporate comprehensive external factors such as weather and holidays or provide a real-time mobile inventory recommendation system, leaving scope for future research.'
        }
    ]
}
sections.append(sec1)

# SECTION 2
sec2 = {
    'title': 'Section 2 — Small/Sparse Data Forecasting',
    'papers': [
        {
            'title': 'Performance Analysis of Time Series Models to Predict Sales Activity of SMEs',
            'details': '**Author(s) & Year:** Justine Christian Susanto et al. (2026)\n**Model/Method used:** XGBoost regression, 7-day Moving Average (MA(7)).\n**Connection to our PS / gap:** Addresses data scarcity gap (1) focusing on zero-inflation which is common in small businesses.',
            'paragraph': 'Forecasting for small enterprises is frequently complicated by highly irregular demand patterns and data sparsity. Susanto et al. (2026) investigated the efficacy of time-series models in predicting sales for an SME operating under a pre-order framework, a system characterized by sporadic demand spikes and high frequencies of zero-transaction days (zero inflation). The authors benchmarked an XGBoost regression model against a simple 7-day Moving Average. They discovered that despite its sophistication, XGBoost struggled to accurately capture the discontinuous nature of the pre-order data, with the basic moving average providing more stable baseline estimates. The study concluded that continuous regression models are fundamentally challenged by zero-inflated, low-volume data environments. This directly highlights the exact data scarcity gap that LocalDemand addresses. By acknowledging that standard regression models fail under sparse conditions, LocalDemand utilizes Facebook Prophet—which inherently handles missing data points and trend shifts more gracefully—and incorporates external regressors to stabilize predictions even when historical daily sales volumes are intermittent or zero-inflated.'
        },
        {
            'title': 'LSTM-Based Hourly Sales Forecasting in SME Food and Beverage Retail',
            'details': '**Author(s) & Year:** Moch Azis Munawar, Ivan Diryana Sudirman (2026)\n**Model/Method used:** LSTM, Naive Forecast, 7-hour Moving Average (MA7), Daily Seasonal Naive.\n**Connection to our PS / gap:** Targets the forecast-to-action gap (3) using cost-based simulations.',
            'paragraph': 'The volatility of hourly sales in the food and beverage industry frequently causes inventory mismatches, leading to either costly spoilage or missed revenue. Munawar and Sudirman (2026) explored this issue by applying an LSTM network to forecast hourly ice cream sales in a culinary SME, benchmarking it against Naive, Moving Average, and Daily Seasonal Naive models. Their findings established that the LSTM model achieved the lowest MAE and RMSE by successfully capturing complex intra-day seasonal patterns that baseline models missed. Crucially, the authors extended their analysis to include cost-based simulations, demonstrating that LSTM-driven predictions actively reduce the financial penalties associated with overstocking and understocking. However, the authors explicitly acknowledged a major limitation: the model did not incorporate external drivers such as weather, holidays, or promotional events. LocalDemand directly addresses this recognized limitation. By utilizing Facebook Prophet configured with exogenous regressors for weather and holidays, LocalDemand captures the external demand shocks that purely autoregressive models miss, ultimately providing a more robust foundation for its automated restock recommendations.'
        }
    ]
}
sections.append(sec2)

# SECTION 3
sec3 = {
    'title': 'Section 3 — SME AI/ML Adoption',
    'papers': [
        {
            'title': 'Optimizing Supply Chain Management for Small and Medium-Sized Businesses Using AI: A Comparative Analysis of GPT-4.5, Grok 3, Gemini 2.0, and DeepSeek R-1',
            'details': '**Author(s) & Year:** Shreeyash Vyakarnam et al. (2025)\n**Model/Method used:** Generative AI (GPT-4.5, Grok 3, Gemini 2.0, DeepSeek R-1), XGBoost, Random Forest.\n**Connection to our PS / gap:** Explores accessibility gap (2) using low-cost GenAI for SMBs.',
            'paragraph': 'As the capabilities of generative AI expand, its applicability to supply chain optimization for small and medium-sized businesses (SMBs) has garnered significant attention. Vyakarnam et al. (2025) conducted a comparative analysis of prominent generative models—including GPT-4.5, Grok 3, Gemini 2.0, and DeepSeek R-1—evaluating their capacity to execute demand planning and logistics tasks typically reserved for expensive ERP systems. While models like DeepSeek R-1 demonstrated promise in synthesizing demand planning insights from retail datasets, the authors found that all generative models failed to resolve complex, deterministic mathematical challenges such as the Vehicle Routing Problem. This reveals a critical limitation: while generative AI is highly accessible and cost-effective, it is fundamentally unsuited for rigorous numerical optimization in supply chains. This finding strongly supports the architectural decision behind LocalDemand. Rather than relying on generalized LLMs for mathematical forecasting, LocalDemand employs Facebook Prophet—a dedicated, purpose-built statistical engine—to ensure that inventory predictions are mathematically sound while maintaining the accessibility SMBs require.'
        },
        {
            'title': 'Technology Acceptance and Security Influences on AI Adoption among Small and Medium Enterprises',
            'details': '**Author(s) & Year:** Yuniarty et al. (2025)\n**Model/Method used:** PLS-SEM on survey data based on TAM.\n**Connection to our PS / gap:** Strongly reinforces accessibility gap (2) showing security and ease of use are critical over pure predictive power.',
            'paragraph': 'The technological superiority of an AI model does not guarantee its adoption by small business owners. Yuniarty et al. (2025) explored this phenomenon by applying the Technology Acceptance Model (TAM) to survey 131 SME owners in Indonesia regarding their intention to adopt AI tools. Utilizing Partial Least Squares–Structural Equation Modeling (PLS-SEM), the researchers discovered that perceived ease of use and perceived security were the primary drivers of technology adoption. Surprisingly, the perceived usefulness (the actual functional capability) of the AI did not significantly drive adoption intention if the system was deemed difficult to use or insecure. This finding is highly consequential for the design of forecasting tools in the SME sector, directly highlighting the technological accessibility gap. It confirms that providing a mathematically sound forecast is insufficient; the delivery mechanism must be friction-less. LocalDemand is architected around this exact behavioral insight. By abstracting the complex Facebook Prophet mathematics behind a simple, secure, and intuitive Flutter mobile interface, LocalDemand ensures that the barrier to entry for SME owners is minimized, driving actual adoption and practical utility.'
        },
        {
            'title': 'Technology Adoption of MSMEs in Food Supply Chain: The Role of AI in Traceability and Transparency',
            'details': '**Author(s) & Year:** Teerarat Aree, Pittawat Ueasangkomsate (2025)\n**Model/Method used:** Linear regression analysis on survey data.\n**Connection to our PS / gap:** Validates the accessibility gap (2) by confirming that MSMEs face severe financial and educational barriers to AI adoption.',
            'paragraph': 'The integration of AI into food supply chains offers significant operational benefits, yet its penetration into the micro, small, and medium enterprise (MSME) sector remains stalled by resource constraints. Aree and Ueasangkomsate (2025) investigated the role of AI in enhancing traceability and transparency among 92 MSMEs in the Thai food supply chain. Through linear regression analysis, the study confirmed that AI adoption significantly improves supply chain integrity and firm performance. Crucially, however, the authors identified a massive barrier to entry: MSMEs fundamentally lack both the financial capital and the technical "know-how" required to invest in and operate standard AI solutions. This directly validates the accessibility gap that LocalDemand seeks to bridge. The study underscores that enterprise-grade AI supply chain solutions are economically and operationally out of reach for micro-businesses. By delivering automated inventory forecasting through a low-cost, low-code mobile platform, LocalDemand democratizes access to AI, allowing SMEs to optimize their supply chains without requiring dedicated IT budgets or data science expertise.'
        },
        {
            'title': 'Factors influencing audit quality through the acceptance and use of AI by auditors in Thailand, affiliated with SMEs audit firms',
            'details': '**Author(s) & Year:** Kacha Somjaipeng, Watchareewan Jitsakul (2026)\n**Model/Method used:** Technology Acceptance Model (TAM), PLS-SEM.\n**Connection to our PS / gap:** Informs accessibility gap (2) from a behavioral standpoint.',
            'paragraph': 'Understanding the behavioral and environmental drivers behind SME technology adoption is critical for ensuring the successful deployment of AI solutions. Somjaipeng and Jitsakul (2026) utilized the Technology-Organization-Environment (TOE) framework and the Technology Acceptance Model (TAM) to evaluate AI adoption among 120 SME-affiliated auditors in Thailand. Using PLS-SEM analysis, they found that environmental factors—particularly regulatory frameworks—had a significant positive influence (β = 0.562) on the perceived benefits of AI, explaining over 70% of the variance in AI acceptance. Although this study operates within the auditing sector rather than food service, it yields a crucial insight for the development of SME-focused technology: algorithmic superiority alone does not guarantee adoption. Solutions must be perceived as highly beneficial and environmentally aligned with the user’s daily constraints. This principle underpins the design philosophy of LocalDemand, which addresses the SME accessibility gap by wrapping complex Prophet forecasting within an intuitive, highly accessible Flutter mobile interface that requires minimal technical expertise from the business owner.'
        },
        {
            'title': 'Predictive Marketing and Sales Analytics Using Machine Learning for Small and Medium E-Commerce Enterprises',
            'details': '**Author(s) & Year:** Swati Srivastava et al. (2026)\n**Model/Method used:** Classification, regression, and ensemble learning framework proposition.\n**Connection to our PS / gap:** Confirms accessibility gap (2) regarding budget and model complexity barriers.',
            'paragraph': 'The transition from reactive to predictive analytics remains a significant hurdle for smaller digital businesses. Srivastava et al. (2026) provided a comprehensive review of how machine learning—specifically regression, classification, and ensemble methods—can be leveraged by small and medium e-commerce enterprises for demand forecasting and targeted marketing. While the authors effectively argue that machine learning dramatically outperforms traditional statistical summaries by capturing dynamic consumer behavior, their primary contribution lies in identifying the barriers to entry. The study highlights that budget constraints, perceived model complexity, and inadequate data infrastructure prevent widespread ML adoption among SMEs. Although this research is largely theoretical and lacks empirical error metrics, it perfectly frames the "accessibility gap" that plagues the SME sector. It validates the core premise of LocalDemand: for advanced predictive analytics to be viable for small businesses, they must be abstracted away from complex data infrastructure and delivered through highly accessible, user-friendly mobile interfaces that require zero technical expertise to operate.'
        }
    ]
}
sections.append(sec3)

for sec in sections:
    append_section(sec['title'], sec['papers'])
